<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="1" hostname="laptop-PC" name="com.xaviar.service.CallLogServiceTests" tests="1" time="2.081" timestamp="2013-08-05T04:19:45">
  <properties />
  <testcase classname="com.xaviar.service.CallLogServiceTests" name="testSomething" time="1.852">
    <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at com.xaviar.service.CallLogServiceTests.testSomething(CallLogServiceTests.groovy:15)
</failure>
  </testcase>
  <system-out><![CDATA[--Output from testSomething--
]]></system-out>
  <system-err><![CDATA[--Output from testSomething--
]]></system-err>
</testsuite>
